apiVersion: extensions/v1beta1
kind: Service
metadata:
  name: addressbook-service
  labels:
    app: addressbook-project
spec:
  selector:
    app: addressbook-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
