apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: addressbook-deployment
spec:
  selector:
    matchLabels:
      app: addressbook-project
  replicas: 2 
  template:
    metadata:
      labels:
        app: addressbook-project
    spec:
      containers:
      - name: addressbook-project
        image: daidasunny/addressbook
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
